backend:
  name: github
  branch: master
  repo: danielballoch/ecom
  site_domain: musing-ardinghelli-c4017a.netlify.com

media_folder: static/assets
public_folder: assets

collections:
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    fields:
      - { name: "name", label: "Name" }
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "product"}
      - { name: "price", label: "Price" }
      - { name: "weight", label: "Weight" }
      - { name: "description", label: "Description", wiget: "markdown" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}