backend:
  name: github
  branch: master
  repo: danielballoch/ecom
  site_domain: musing-ardinghelli-c4017a.netlify.com
  publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    fields:
      - { name: "name", label: "Name" }
      - { name: "templateKey", label: "Template Key", widget: "hidden", default: "product"}
      - { name: "price", label: "Price" }
      - { name: "color", label: "Color" }
      - { name: "tags", label: "Tags" }
      - { name: "sizes", label: "Sizes" }
      - { name: "weight", label: "Weight" }
      - { name: "details", label: "Description", wiget: "markdown" }


# posttype: "product"
# name: 511 slim jeans
# templateKey: product
# id: 1
# price: 65.00
# weight: 1
# image: "../511_slim_jeans/511_slim_jeans_front.jpg"
# path: "/products/511_slim_jeans/511_slim_jeans"
# date: "2019-11-07"
# tags: ['jean']
# color: ['all','black']
# details: ['Material: 99% Cotton & 1% Elastane', 'Size & fit Length: Inside Leg: 80cm; Front Rise: 26cm; Leg Opening: 38cm','Care: Cold machine wash. Do not tumble dry. Warm iron.','brand donates 1% or more of all profits to a charitable cause',]
# sizes: ['W29/L32','W30/L32','W31/L32','W32/L32','W34/L34']
 